### ISSUE TITLE
Add <^> simbol

### ISSUE THREAD

**Issue by Mymoprohodil** [ryjjin/Obsidian-shortcuts-extender#1]
It will be very kind of you to add symbol `^` (for example, while pressing `Alt`+`6`). Thank you!

Спасибо! Очень удобный плагин!
Obsidian развивается - было бы неплохо добавить символ `^` (крышечка), например, при нажатии `Alt`+`6` (цифра шесть).
Еще раз спасибо!

**Comment by ryjjin** [comment]
@Mymoprohodil  Спасибо за отзыв! Добавлю на выходных

**Comment by ryjjin** [comment]
@Mymoprohodil Можете обновить плагин. Внесены изменения:

- добавлены шорткаты на ^ { } 
- шорткаты по умолчанию продублированы в настройках на EN раскладку 
- символ комментария теперь по умолчанию вызывается не на <Alt + Shift+ б>, а на <Alt+ б> 
- если ввести сочетание клавиш для комментария - символ > введется с отступом после него (на самом деле это незапланированный баг, который у меня сходу не удалось устранить)
- если выделить несколько строк текста и нажать сочетание клавиш для ввода >, закомментится каждая строка

**Comment by Mymoprohodil** [comment]
да!
крышечка, понимание английской раскладки, "умная" вставка символов...
так стало намного удобнее!
огромное СПАСИБО!!!

**Comment by Mymoprohodil** [comment]
"|" - так еще удобнее стало! Спасибо! Пользуюсь с большим удовольствием! :)
