### ISSUE TITLE
I want it to work on Obsidian mobile.

### ISSUE THREAD

**Issue by jun3010me** [ryjjin/Obsidian-shortcuts-extender#11]
I have installed your plugin on Obsidian Mobile. I hope you can make it work on the iPad. Please help me.

**Comment by ryjjin** [comment]
Hey! Sorry for the long answer, I absolutely did not know which side to approach. In the end, the community helped to solve the problem.

Update the plugin to version 2.0.2, it now works on iPad.
Let me know if anything goes wrong.
