### ISSUE TITLE
Not working since native WYSIWYG insider release

### ISSUE THREAD

**Issue by ryadaj** [ryjjin/Obsidian-shortcuts-extender#13]
Since native WYSIWYG insider release, I can no longer use my hotkeys to change a selection into a header or a list

Thanks for an amazing plugin! Have loved using it.

**Comment by that0n3guy** [comment]
I can verify this.  Probably because of codemirror update?

**Comment by ryadaj** [comment]
Yes I think so 

—
Ryan Johnson
+1 (519) 216-1372

**Comment by ryjjin** [comment]
Hi! Thanks for information, I have not tried this function yet. 
I will think about whether I can fix it on my own, maybe will hiring a developer for fixes

**Comment by ryadaj** [comment]
Thanks for a great plugin and for all your hard work!

—
Ryan Johnson
+1 (519) 216-1372

**Comment by claremacrae** [comment]
I've asked in #plugin-dev on the Obsidian Members Group Discord to see if anyone has any tips on the kinds of changes required, to update and work with Live Preview mode, whilst still working on previous versions too.

**Comment by ryadaj** [comment]
Awesome, thank you ☺️

—
Ryan Johnson
+1 (519) 216-1372

**Comment by claremacrae** [comment]
You're welcome - there were some good tips - I'll write them up soon...

(@ryadaj in case you don't know, GitHub is including you phone number in all your emailed comments?)

**Comment by ryadaj** [comment]
Wow, you are a kind one! Thank you so much, I've gone through and updated my comments to remove that info!

**Comment by that0n3guy** [comment]
Just a heads up... https://github.com/argenos/nldates-obsidian just updated their plugin to work w/ "live preview"   Maybe you can see what they did for a quick reference point... Here is a quick link that might help: https://github.com/argenos/nldates-obsidian/pull/57

**Comment by ryadaj** [comment]
Awesome thank you ☺️🙏

**Comment by claremacrae** [comment]
> I've asked in #plugin-dev on the Obsidian Members Group Discord to see if anyone has any tips on the kinds of changes required, to update and work with Live Preview mode, whilst still working on previous versions too.

So the initial conclusion was to change uses like this:

```typescript
let editor = activeLeaf.view.sourceMode.cmEditor;
```

To this:

```typescript
let editor = activeLeaf.view.editor;
```

However, this was followed by a statement that:

> You shouldn’t assume the active leaf is a markdown editor. You should do getActiveViewOfType

and

> Yes, but you should also make sure that there actually is a markdown view (as in, get the view, check to make sure it’s not null, then get the editor)

So after further discussion, this sort of thing - taken from code in another plugin, was the recommended approach:

```typescript
    let editor = app.workspace.getActiveViewOfType(MarkdownView)?.editor;
    if (editor == null) {
      return;
    }
```

There was also a recommendation to first create a function like `getEditor()` that would return `app.workspace.getActiveViewOfType(MarkdownView)?.editor;`  - so that if the logic needs to be refined in future, it is only in one place...

This code is expected to work on CM5 and CM6 - including with the new Live Preview/WYSIWYG...

**Comment by claremacrae** [comment]
For anyone reading this who is in the Obsidian Discord, the discussion [starts here, in #plugin-dev](https://discord.com/channels/686053708261228577/840286264964022302/912057547333185546).

**Comment by that0n3guy** [comment]
I started messing with this a little: https://github.com/ryjjin/Obsidian-shortcuts-extender/pull/14

**Comment by ryjjin** [comment]
Thanks for your support and great work.
As I said in the commit branch, most likely, I myself would not have coped with it (or at least it would have taken a whole carriage of time).

Everything works for me too, checked on Windows and Mac.
The new package has been released, the updated version can be installed via Obsidian.

And the most amazing thing is that now the plugin began to work on iOS devices (previously, heading levels did not change when using shortcuts on an iPad)
