### ISSUE TITLE
[bug] Cursor location incorrect on header of blank line

### ISSUE THREAD

**Issue by that0n3guy** [ryjjin/Obsidian-shortcuts-extender#15]
On a blank line, if you hit `ctrl-1` (for example, other headers do the same thing) it puts the cursor before the `#` rather than after.

Here is an image that shows it:
![image](https://user-images.githubusercontent.com/113870/145229556-920e1678-811e-4647-a3ed-3b66bf60af8f.png)

I'm on 0.13.7 (so live preview)

**Comment by ryjjin** [comment]
Hmmm, it's strange. 
This behavior appears only in live preview mode and really only with an empty line (but with all types of titles).
Apparently, in live preview mode, obsidian perceives the `selectedText.end` parameter differently than in classic mode, do you have any ideas about that?

**Comment by ryjjin** [comment]
well, after the last update this works as standard behavior and shows up in all cases

**Comment by gabrielwhite** [comment]
I'm seeing the same issue on 0.13.14

**Comment by ryjjin** [comment]
Fixed by @jonmseaman . Thanks for you great help!

**Comment by Newdea** [comment]
simaliar bug when hit `Alt+>`,  it puts the cursor before the `>` rather than after it.

This behavior appears only in live preview mode and really only with an empty line.
