### ISSUE TITLE
shortcuts do not work with Live Preview enabled

### ISSUE THREAD

**Issue by seanwbarry** [ryjjin/Obsidian-shortcuts-extender#19]
If I use a shortcut - e.g. ctrl+1 - to turn a line of text into Heading 1 - the shortcut does not work if Obsidian is in Live Preview mode.

**Comment by ryjjin** [comment]
Hi! It's strange, we are fix it few weeks ago.
Do you use updated version of plugin? 

P.S.: now functions of plugin work with cursor in line, but don't work with selected text. 
I try to fix it soon (it still works with option "use legacy editor", but this option don't allow to use live preview mode)

**Comment by b1uegh0st** [comment]
Hi @ryjjin , just want to add a case:
- With Live Preview enabled.
- If I start in a blank line.
- Use `header level x` shortcut
- The cursor will be before the `####` 

Hope this can be fixed soon. Thanks for the great plugin. I use it a lot.

![image](https://user-images.githubusercontent.com/6695697/147593922-c7a4d1f3-e084-4b5e-a456-6e2bc89bacbb.png)

**Comment by claremacrae** [comment]
> Hi @ryjjin , just want to add a case:
> 
> * With Live Preview enabled.
> * If I start in a blank line.
> * Use `header level x` shortcut
> * The cursor will be before the `####`

I came here to mention exactly the cursor positioning problem. It's really tripping up my muscle memory :-)

**Comment by ryjjin** [comment]
Hi! Please update the plugin, now it shall work properly
