### ISSUE TITLE
Shortcut for @, $, &

### ISSUE THREAD

**Issue by MitPitt** [ryjjin/Obsidian-shortcuts-extender#4]
Please add a shortcut option Alt+2 for input @, Alt+4 for input $, Alt+7 for input &.
Would be useful for me and others, I'm sure.
Thanks in advance!

**Comment by ryjjin** [comment]
Thanks, I'll add in the next couple of days :)

**Comment by ryjjin** [comment]
Well done! You can update through the Obsidian app.

Also added a keyboard shortcut for the "-" character, which works by analogy with ">": if you select several lines, then all selected lines will be converted into an unordered list (the first line must be selected in its entirety, in the next versions I will try to get away from this limitation)
