### ISSUE TITLE
(Feature Request) Apply heading level change to multiple lines at once

### ISSUE THREAD

**Issue by AngelusDomini** [ryjjin/Obsidian-shortcuts-extender#5]
Sometimes I'll use multiple text cursors on a number of lines or select those number of lines to give them all the same heading level, but right now with this plugin it only applies to one line. Is it possible to have that feature implemented?

As an example, one of Obsidian's core features is to toggle checklist status which can be done for multiple lines. From another plugin: Hotkeys++, we can toggle ordered and unordered lists for multiple lines.

**Comment by ryjjin** [comment]
Thanks for your feedback!
For lists, citations and other continuously selected text changes apply to each selected line, like in Hotkeys++.

I already tried to do this for multiple text cursors, but the first attempts led to the fact that all lines between cursors changed. 
I will try to communicate with the Obsidian developers later and make such an update in the next version of the plugin

**Comment by ryjjin** [comment]
@AngelusDomini We have a wonderful community :) Please update the plugin!
