### ISSUE TITLE
Insert code block

### ISSUE THREAD

**Issue by captaincaed** [ryjjin/Obsidian-shortcuts-extender#7]
I really like this plugin, thank you!  Having the headers easy to type is very nice.

It would be nice to have a shortcut for an entire code block as well, with the cursor at the end of the top three ticks, so you can write your language right  away:

```<cursor location>
 <foo>
```

Thanks for the consideration!

**Comment by ryjjin** [comment]
Sorry, i really forgot about it. Now it works with shortcut `ctrl` + `

**Comment by Slava-Nik** [comment]
Useful plugin, I like it. It would be great to also add a feature of inserting code blocks with different languages. Something like that. Thanks

```
this.addCommand({
        id: "shortcut-code-block-go",
        name: "Shortcut for toggling a ts code block",
        callback: function () { return _this.shortcutToggleCodeBlock('go'); },
        hotkeys: [
            {
                modifiers: ["Ctrl"],
                key: "g",
            },
        ],
    });
    this.addCommand({
        id: "shortcut-code-block-js",
        name: "Shortcut for toggling a ts code block",
        callback: function () { return _this.shortcutToggleCodeBlock('javascript'); },
        hotkeys: [
            {
                modifiers: ["Ctrl"],
                key: "j",
            },
        ],
});
```
