### ISSUE TITLE
Markdown headings shortcut using Cmd on Mac

### ISSUE THREAD

**Issue by sambody** [ryjjin/Obsidian-shortcuts-extender#8]
Feature request: I would like to use the shortcut Command-1/2/3 to get the markdown headings, instead of Control-1/2/3 — since I already use this shortcut in other software on Mac (Libreoffice headings, markdown headings in IA Writer). Would that be possible? I have done a quick test by replacing `modifiers: ["Ctrl"]` with `modifiers: ["Cmd"]` but that didn't work. 
Thanks.

**Comment by ryjjin** [comment]
Hi!
You can rechange shortcuts via Obsidian app: 
```
Settings -> Hotkeys -> Shortcuts extender: line into level X heading
```

I test it on my mac and it works

**Comment by sambody** [comment]
Yes, it works! Fantastic. It was one of the few things that bugged me with Obsidian, and now it is solved. Thank you so much for this.
